#!/usr/bin/env python3
"""Generate Markdown, HTML, SVG, and PNG benchmark reports."""

from __future__ import annotations

import argparse
import csv
import html
import json
import shutil
import sys
from pathlib import Path
from typing import Any

import matplotlib.pyplot as plt


TARGETS = ("nginx", "caddy", "raddex")
TARGET_LABELS = {"nginx": "Nginx", "caddy": "Caddy", "raddex": "Raddex"}
TARGET_COLORS = {"nginx": "#5b6573", "caddy": "#2f80ed", "raddex": "#e45756"}
CHARTS = {
    "throughput_pct": {
        "filename": "throughput",
        "title": "Relative maximum stable throughput (Nginx = 100%; higher is better)",
        "ylabel": "Throughput (% of Nginx)",
    },
    "p99_pct": {
        "filename": "latency-p99",
        "title": "Relative p99 latency at the reference load (Nginx = 100%; lower is better)",
        "ylabel": "p99 latency (% of Nginx)",
    },
    "cpu_per_request_pct": {
        "filename": "cpu-per-request",
        "title": "Relative CPU cost per request (Nginx = 100%; lower is better)",
        "ylabel": "CPU ms/request (% of Nginx)",
    },
    "memory_pct": {
        "filename": "memory",
        "title": "Relative peak memory at the reference load (Nginx = 100%; lower is better)",
        "ylabel": "Peak memory (% of Nginx)",
    },
}


def load_summary(path: Path) -> dict[str, Any]:
    """Load and minimally validate a collected benchmark summary.

    Args:
        path: JSON summary generated by ``collect.py``.

    Returns:
        Decoded summary object.

    Raises:
        ValueError: If the summary has no normalized records.
        OSError: If the summary cannot be read.
    """

    summary = json.loads(path.read_text(encoding="utf-8"))
    if not isinstance(summary, dict) or not summary.get("normalized"):
        raise ValueError(f"summary has no normalized benchmark records: {path}")
    return summary


def format_bytes(value: float) -> str:
    """Format a byte count for human-readable report tables.

    Args:
        value: Number of bytes.

    Returns:
        A decimal byte string with a binary unit.
    """

    units = ("B", "KiB", "MiB", "GiB", "TiB")
    amount = float(value)
    for unit in units:
        if abs(amount) < 1024 or unit == units[-1]:
            return f"{amount:.2f} {unit}"
        amount /= 1024
    return f"{amount:.2f} TiB"


def format_metric(value: float, metric: str) -> str:
    """Format one raw metric for a Markdown or HTML table.

    Args:
        value: Metric value.
        metric: Metric name.

    Returns:
        A concise formatted string.
    """

    if metric == "memory_peak_bytes":
        return format_bytes(value)
    if metric == "error_rate":
        return f"{value * 100:.3f}%"
    if metric == "qps":
        return f"{value:.2f}"
    return f"{value:.3f}"


def scenario_order(summary: dict[str, Any]) -> list[str]:
    """Return scenario IDs in the order used by the collected measurements."""

    seen: list[str] = []
    for item in summary["normalized"]:
        if item["scenario_id"] not in seen:
            seen.append(item["scenario_id"])
    return seen


def normalized_by_scenario(summary: dict[str, Any]) -> dict[str, dict[str, dict[str, Any]]]:
    """Index normalized records by scenario and target."""

    indexed: dict[str, dict[str, dict[str, Any]]] = {}
    for item in summary["normalized"]:
        indexed.setdefault(item["scenario_id"], {})[item["target"]] = item
    return indexed


def create_chart(summary: dict[str, Any], metric: str, output_dir: Path) -> tuple[Path, Path]:
    """Create one relative-comparison chart in SVG and PNG formats.

    Args:
        summary: Collected benchmark summary.
        metric: Normalized metric key from ``CHARTS``.
        output_dir: Directory receiving the chart files.

    Returns:
        Paths to the SVG and PNG files.

    Raises:
        ValueError: If a required target or metric is missing.
        OSError: If the output cannot be written.
    """

    chart = CHARTS[metric]
    indexed = normalized_by_scenario(summary)
    scenario_ids = scenario_order(summary)
    labels = []
    values: dict[str, list[float]] = {target: [] for target in TARGETS}
    for scenario_id in scenario_ids:
        targets = indexed[scenario_id]
        labels.append(targets["nginx"]["title"])
        for target in TARGETS:
            try:
                values[target].append(float(targets[target]["metrics"][metric]))
            except KeyError as error:
                raise ValueError(f"missing {metric} for {scenario_id} / {target}") from error

    output_dir.mkdir(parents=True, exist_ok=True)
    positions = list(range(len(labels)))
    width = 0.24
    fig, axis = plt.subplots(figsize=(max(10, len(labels) * 1.7), 6.5))
    for index, target in enumerate(TARGETS):
        offset = (index - 1) * width
        bars = axis.bar(
            [position + offset for position in positions],
            values[target],
            width,
            label=TARGET_LABELS[target],
            color=TARGET_COLORS[target],
        )
        axis.bar_label(bars, fmt="%.0f", padding=3, fontsize=8)
    axis.axhline(100, color="#333333", linewidth=0.9, linestyle="--", label="Nginx baseline")
    axis.set_title(chart["title"])
    axis.set_ylabel(chart["ylabel"])
    axis.set_xticks(positions, labels, rotation=22, ha="right")
    axis.set_ylim(bottom=0)
    axis.grid(axis="y", alpha=0.25)
    axis.set_axisbelow(True)
    axis.legend(ncol=4, loc="upper center", bbox_to_anchor=(0.5, -0.17), frameon=False)
    fig.tight_layout()

    svg_path = output_dir / f"{chart['filename']}.svg"
    png_path = output_dir / f"{chart['filename']}.png"
    fig.savefig(svg_path, format="svg")
    fig.savefig(png_path, format="png", dpi=160)
    plt.close(fig)
    return svg_path, png_path


def primary_table(summary: dict[str, Any]) -> str:
    """Render raw reference-load and stable-throughput values as Markdown."""

    rows = [
        "| Scenario | Target | Reference load | Max stable QPS | Reference p99 | Error rate | CPU ms/request | Peak memory |",
        "| --- | --- | ---: | ---: | ---: | ---: | ---: | ---: |",
    ]
    for item in summary["normalized"]:
        metrics = item["reference_metrics"]
        rows.append(
            "| {title} | {target} | {load} | {qps} | {p99} ms | {error} | {cpu} | {memory} |".format(
                title=item["title"],
                target=TARGET_LABELS[item["target"]],
                load=item["reference_load"],
                qps=format_metric(item["max_stable_qps"], "qps"),
                p99=format_metric(metrics["p99_ms"], "p99_ms"),
                error=format_metric(metrics["error_rate"], "error_rate"),
                cpu=format_metric(metrics["cpu_ms_per_request"], "cpu_ms_per_request"),
                memory=format_metric(metrics["memory_peak_bytes"], "memory_peak_bytes"),
            )
        )
    return "\n".join(rows)


def normalized_table(summary: dict[str, Any]) -> str:
    """Render the percentage values used by the charts as Markdown."""

    rows = [
        "| Scenario | Target | Throughput | p99 latency | CPU/request | Memory | Error rate |",
        "| --- | --- | ---: | ---: | ---: | ---: | ---: |",
    ]
    for item in summary["normalized"]:
        metrics = item["metrics"]
        rows.append(
            "| {title} | {target} | {throughput:.1f}% | {p99:.1f}% | {cpu:.1f}% | {memory:.1f}% | {error:.3f}% |".format(
                title=item["title"],
                target=TARGET_LABELS[item["target"]],
                throughput=metrics["throughput_pct"],
                p99=metrics["p99_pct"],
                cpu=metrics["cpu_per_request_pct"],
                memory=metrics["memory_pct"],
                error=metrics["error_rate"] * 100,
            )
        )
    return "\n".join(rows)


def write_markdown(summary: dict[str, Any], output: Path) -> None:
    """Write the human-readable Markdown report.

    Args:
        summary: Collected benchmark summary.
        output: Markdown output path.

    Returns:
        None.

    Raises:
        OSError: If the report cannot be written.
    """

    manifest = summary["manifest"]
    chart_lines = []
    for chart in CHARTS.values():
        chart_lines.append(f"![{chart['title']}](charts/{chart['filename']}.svg)")
    content = "\n".join(
        [
            "# Raddex benchmark report",
            "",
            "This report compares Nginx, Caddy, and Raddex within each scenario.",
            "Nginx is the baseline: `100%` means `1.00x`. Percentages are not",
            "combined into a single score.",
            "",
            f"- Profile: `{manifest['profile']}`",
            f"- Raddex commit: `{manifest['raddex_commit']}`",
            f"- Run ID: `{manifest['run_id']}`",
            "",
            "## Relative charts",
            "",
            *chart_lines,
            "",
            "## Normalized results",
            "",
            normalized_table(summary),
            "",
            "## Raw reference metrics",
            "",
            primary_table(summary),
            "",
            "## Interpretation",
            "",
            "- Throughput above 100% is higher than Nginx at the selected stable point.",
            "- Latency, CPU, and memory below 100% are lower than Nginx.",
            "- Error rate is shown as an absolute percentage and is not normalized.",
            "- Results from different machines must not be merged by absolute QPS.",
            "",
        ]
    )
    output.write_text(content, encoding="utf-8")


def write_html(summary: dict[str, Any], output: Path) -> None:
    """Write a self-contained HTML report referencing the generated SVG files.

    Args:
        summary: Collected benchmark summary.
        output: HTML output path.

    Returns:
        None.

    Raises:
        OSError: If the report cannot be written.
    """

    manifest = summary["manifest"]
    images = "\n".join(
        f'<figure><img src="charts/{html.escape(chart["filename"])}.svg" alt="{html.escape(chart["title"])}"><figcaption>{html.escape(chart["title"])}</figcaption></figure>'
        for chart in CHARTS.values()
    )
    table = html.escape(normalized_table(summary)).replace("\n", "<br>\n")
    content = f"""<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Raddex benchmark report</title>
  <style>
    body {{ font-family: system-ui, sans-serif; margin: 2rem auto; max-width: 1100px; line-height: 1.5; }}
    figure {{ margin: 2rem 0; }}
    img {{ max-width: 100%; border: 1px solid #ddd; }}
    figcaption {{ color: #555; margin-top: .5rem; }}
    code {{ background: #f2f2f2; padding: .1rem .3rem; }}
  </style>
</head>
<body>
  <h1>Raddex benchmark report</h1>
  <p>Nginx is the baseline: <code>100%</code> means <code>1.00x</code>.</p>
  <ul>
    <li>Profile: <code>{html.escape(str(manifest['profile']))}</code></li>
    <li>Raddex commit: <code>{html.escape(str(manifest['raddex_commit']))}</code></li>
    <li>Run ID: <code>{html.escape(str(manifest['run_id']))}</code></li>
  </ul>
  {images}
  <h2>Normalized results</h2>
  <pre>{table}</pre>
</body>
</html>
"""
    output.write_text(content, encoding="utf-8")


def write_csv(summary: dict[str, Any], output: Path) -> None:
    """Write aggregated raw and normalized measurements as CSV.

    Args:
        summary: Collected benchmark summary.
        output: CSV output path.

    Returns:
        None.

    Raises:
        OSError: If the CSV cannot be written.
    """

    fieldnames = [
        "scenario_id",
        "title",
        "target",
        "scheme",
        "protocol",
        "path",
        "load_model",
        "load",
        "reference_load",
        "max_stable_load",
        "max_stable_qps",
        "qps",
        "success_rate",
        "error_rate",
        "p50_ms",
        "p95_ms",
        "p99_ms",
        "max_ms",
        "cpu_avg_percent",
        "cpu_peak_percent",
        "memory_peak_bytes",
        "cpu_ms_per_request",
        "throughput_pct",
        "p99_pct",
        "cpu_per_request_pct",
        "memory_pct",
    ]
    normalized = normalized_by_scenario(summary)
    raw_by_key = {
        (item["scenario_id"], item["target"]): item
        for item in summary["primary"]
    }
    output.parent.mkdir(parents=True, exist_ok=True)
    with output.open("w", newline="", encoding="utf-8") as stream:
        writer = csv.DictWriter(stream, fieldnames=fieldnames)
        writer.writeheader()
        for scenario_id in scenario_order(summary):
            for target in TARGETS:
                item = normalized[scenario_id][target]
                raw = raw_by_key[(scenario_id, target)]
                reference = raw["reference_metrics"]
                row = {
                    "scenario_id": scenario_id,
                    "title": item["title"],
                    "target": target,
                    "scheme": item["scheme"],
                    "protocol": item["protocol"],
                    "path": item["path"],
                    "load_model": item["load_model"],
                    "load": item["reference_load"],
                    "reference_load": item["reference_load"],
                    "max_stable_load": item["max_stable_load"],
                    "max_stable_qps": item["max_stable_qps"],
                    **reference,
                    **item["metrics"],
                }
                writer.writerow({field: row.get(field, "") for field in fieldnames})


def generate_report(summary_path: Path, output_dir: Path, public_dir: Path) -> None:
    """Generate all report formats and refresh the stable public SVG assets.

    Args:
        summary_path: Collected summary JSON.
        output_dir: Run-specific report directory.
        public_dir: Stable directory used by README and the docs site.

    Returns:
        None.

    Raises:
        ValueError: If the summary is incomplete.
        OSError: If an output cannot be written.
    """

    summary = load_summary(summary_path)
    chart_dir = output_dir / "charts"
    chart_dir.mkdir(parents=True, exist_ok=True)
    public_dir.mkdir(parents=True, exist_ok=True)
    for metric in CHARTS:
        svg_path, _ = create_chart(summary, metric, chart_dir)
        shutil.copy2(svg_path, public_dir / svg_path.name)
    write_markdown(summary, output_dir / "report.md")
    write_html(summary, output_dir / "report.html")
    write_csv(summary, output_dir / "summary.csv")


def parse_args() -> argparse.Namespace:
    """Parse report generator arguments."""

    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--summary", type=Path, required=True)
    parser.add_argument("--output-dir", type=Path, required=True)
    parser.add_argument("--public-dir", type=Path, required=True)
    return parser.parse_args()


def main() -> int:
    """Run report generation and return a shell-friendly status code."""

    args = parse_args()
    try:
        generate_report(args.summary, args.output_dir, args.public_dir)
        return 0
    except (OSError, ValueError, json.JSONDecodeError) as error:
        print(f"report error: {error}", file=sys.stderr)
        return 1


if __name__ == "__main__":
    raise SystemExit(main())
